In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
import seaborn as sn
from sklearn.model_selection import train_test_split
import wget

In [14]:
fruits = pd.read_table('fruit_data_with_colors.txt')
fruits.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [15]:
# create a mapping from fruit label value to fruit name to make results easier to interpret
lookup_fruit_name = dict(zip(fruits.fruit_label.unique(), fruits.fruit_name.unique()))   
lookup_fruit_name

{1: 'apple', 2: 'mandarin', 3: 'orange', 4: 'lemon'}

In [16]:
fruits.shape

(59, 7)

In [17]:
for i in fruits.fruit_label.unique():
    print(i,":",len(fruits[fruits['fruit_label']==i]),"(",lookup_fruit_name[i],")")

1 : 19 ( apple )
2 : 5 ( mandarin )
3 : 19 ( orange )
4 : 16 ( lemon )


In [18]:
fruits2=fruits[:]

In [19]:
fruits2.fruit_subtype.unique()

array(['granny_smith', 'mandarin', 'braeburn', 'golden_delicious',
       'cripps_pink', 'spanish_jumbo', 'selected_seconds', 'turkey_navel',
       'spanish_belsan', 'unknown'], dtype=object)

In [20]:
fruits2.fruit_subtype.unique()[0]

'granny_smith'

In [21]:
lookup_fruit_name2 = dict()
lookup_fruit_name2

{}

In [22]:
c = fruits2.fruit_subtype.unique()
cc = len(c)
cc

10

In [23]:
for i in range(cc):
    lookup_fruit_name2[fruits2.fruit_subtype.unique()[i]] = i
lookup_fruit_name2

{'granny_smith': 0,
 'mandarin': 1,
 'braeburn': 2,
 'golden_delicious': 3,
 'cripps_pink': 4,
 'spanish_jumbo': 5,
 'selected_seconds': 6,
 'turkey_navel': 7,
 'spanish_belsan': 8,
 'unknown': 9}

In [24]:
o = fruits2.fruit_subtype
oo = len(o)
fruit_label2 = np.zeros(oo)

for i in range(oo):
    p = o[i]
    fruit_label2[i] = lookup_fruit_name2[o[i]]

fruit_label2 = np.array(fruit_label2, dtype=int)
fruit_label2

array([0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8,
       8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [25]:
fruits4 = fruits2.assign(fruit_label2 = fruit_label2)
fruits4

fruit_label fruit_name     fruit_subtype  mass  width  height  \
0             1      apple      granny_smith   192    8.4     7.3   
1             1      apple      granny_smith   180    8.0     6.8   
2             1      apple      granny_smith   176    7.4     7.2   
3             2   mandarin          mandarin    86    6.2     4.7   
4             2   mandarin          mandarin    84    6.0     4.6   
5             2   mandarin          mandarin    80    5.8     4.3   
6             2   mandarin          mandarin    80    5.9     4.3   
7             2   mandarin          mandarin    76    5.8     4.0   
8             1      apple          braeburn   178    7.1     7.8   
9             1      apple          braeburn   172    7.4     7.0   
10            1      apple          braeburn   166    6.9     7.3   
11            1      apple          braeburn   172    7.1     7.6   
12            1      apple          braeburn   154    7.0     7.1   
13            1      apple  golden_delicious   164    7.3     7.7   
14            1      apple  golden_delicious   152    7.6     7.3   
15            1      apple  golden_delicious   156    7.7     7.1   
16            1      apple  golden_delicious   156    7.6     7.5   
17            1      apple  golden_delicious   168    7.5     7.6   
18            1      apple       cripps_pink   162    7.5     7.1   
19            1      apple       cripps_pink   162    7.4     7.2   
20            1      apple       cripps_pink   160    7.5     7.5   
21            1      apple       cripps_pink   156    7.4     7.4   
22            1      apple       cripps_pink   140    7.3     7.1   
23            1      apple       cripps_pink   170    7.6     7.9   
24            3     orange     spanish_jumbo   342    9.0     9.4   
25            3     orange     spanish_jumbo   356    9.2     9.2   
26            3     orange     spanish_jumbo   362    9.6     9.2   
27            3     orange  selected_seconds   204    7.5     9.2   
28            3     orange  selected_seconds   140    6.7     7.1   
29            3     orange  selected_seconds   160    7.0     7.4   
30            3     orange  selected_seconds   158    7.1     7.5   
31            3     orange  selected_seconds   210    7.8     8.0   
32            3     orange  selected_seconds   164    7.2     7.0   
33            3     orange      turkey_navel   190    7.5     8.1   
34            3     orange      turkey_navel   142    7.6     7.8   
35            3     orange      turkey_navel   150    7.1     7.9   
36            3     orange      turkey_navel   160    7.1     7.6   
37            3     orange      turkey_navel   154    7.3     7.3   
38            3     orange      turkey_navel   158    7.2     7.8   
39            3     orange      turkey_navel   144    6.8     7.4   
40            3     orange      turkey_navel   154    7.1     7.5   
41            3     orange      turkey_navel   180    7.6     8.2   
42            3     orange      turkey_navel   154    7.2     7.2   
43            4      lemon    spanish_belsan   194    7.2    10.3   
44            4      lemon    spanish_belsan   200    7.3    10.5   
45            4      lemon    spanish_belsan   186    7.2     9.2   
46            4      lemon    spanish_belsan   216    7.3    10.2   
47            4      lemon    spanish_belsan   196    7.3     9.7   
48            4      lemon    spanish_belsan   174    7.3    10.1   
49            4      lemon           unknown   132    5.8     8.7   
50            4      lemon           unknown   130    6.0     8.2   
51            4      lemon           unknown   116    6.0     7.5   
52            4      lemon           unknown   118    5.9     8.0   
53            4      lemon           unknown   120    6.0     8.4   
54            4      lemon           unknown   116    6.1     8.5   
55            4      lemon           unknown   116    6.3     7.7   
56            4      lemon           unknown   116    5.9     8.1   
57

In [26]:
fruits4.shape

(59, 8)

In [27]:
fruits4.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score  \
0            1      apple  granny_smith   192    8.4     7.3         0.55   
1            1      apple  granny_smith   180    8.0     6.8         0.59   
2            1      apple  granny_smith   176    7.4     7.2         0.60   
3            2   mandarin      mandarin    86    6.2     4.7         0.80   
4            2   mandarin      mandarin    84    6.0     4.6         0.79   

   fruit_label2  
0             0  
1             0  
2             0  
3             1  
4             1

In [28]:
def reverse_dict(x):
    q = list(lookup_fruit_name2.keys())[list(lookup_fruit_name2.values()).index(x)]
    return q

In [29]:
reverse_dict(8)

'spanish_belsan'

In [30]:
for i in fruits4.fruit_label2.unique():
    print(i,":",len(fruits4[fruits4['fruit_label2']==i]),"(",reverse_dict(i),")")

0 : 3 ( granny_smith )
1 : 5 ( mandarin )
2 : 5 ( braeburn )
3 : 5 ( golden_delicious )
4 : 6 ( cripps_pink )
5 : 3 ( spanish_jumbo )
6 : 6 ( selected_seconds )
7 : 10 ( turkey_navel )
8 : 6 ( spanish_belsan )
9 : 10 ( unknown )


In [31]:
list(lookup_fruit_name2.keys())[list(lookup_fruit_name2.values()).index(8)]

'spanish_belsan'

In [32]:
len(fruits4[fruits4['fruit_label2']==0])

3

In [33]:
# For this example, we use the mass, width, and height features of each fruit instance
X = fruits4[['mass', 'width', 'height']]
y = fruits4['fruit_label2']

# default is 75% / 25% train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [34]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)

In [35]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [36]:
# second example: a larger, elongated fruit with mass 100g, width 6.3 cm, height 8.5 cm
fruit_prediction = knn.predict([[100,6.3,8.5]])
# lookup_fruit_name2[fruit_prediction[0]]
fruit_prediction[0]

9

In [37]:
reverse_dict(fruit_prediction[0])

'unknown'

In [38]:
# first example: a small fruit with mass 20g, width 4.3 cm, height 5.5 cm
fruit_prediction = knn.predict([[20,4.3,5.5]])
reverse_dict(fruit_prediction[0])

'mandarin'

In [39]:
fruit_prediction = knn.predict([[180,6.5,5]])
reverse_dict(fruit_prediction[0])

'braeburn'

In [40]:
fr_pred = knn.predict(X_test)
fr_pred

array([5, 7, 8, 9, 2, 2, 7, 6, 7, 9, 1, 3, 4, 2, 8])

In [41]:
fr_pred.shape

(15,)

In [42]:
y_test

26    5
35    7
43    8
28    6
11    2
2     0
34    7
46    8
40    7
22    4
4     1
10    2
30    6
41    7
33    7
Name: fruit_label2, dtype: int32

In [43]:
(fr_pred,np.array(y_test))

(array([5, 7, 8, 9, 2, 2, 7, 6, 7, 9, 1, 3, 4, 2, 8]),
 array([5, 7, 8, 6, 2, 0, 7, 8, 7, 4, 1, 2, 6, 7, 7]))

In [44]:
# its not the end, see below
knn.score(X_test,y_test)

0.4666666666666667

In [45]:
fruits4

fruit_label fruit_name     fruit_subtype  mass  width  height  \
0             1      apple      granny_smith   192    8.4     7.3   
1             1      apple      granny_smith   180    8.0     6.8   
2             1      apple      granny_smith   176    7.4     7.2   
3             2   mandarin          mandarin    86    6.2     4.7   
4             2   mandarin          mandarin    84    6.0     4.6   
5             2   mandarin          mandarin    80    5.8     4.3   
6             2   mandarin          mandarin    80    5.9     4.3   
7             2   mandarin          mandarin    76    5.8     4.0   
8             1      apple          braeburn   178    7.1     7.8   
9             1      apple          braeburn   172    7.4     7.0   
10            1      apple          braeburn   166    6.9     7.3   
11            1      apple          braeburn   172    7.1     7.6   
12            1      apple          braeburn   154    7.0     7.1   
13            1      apple  golden_delicious   164    7.3     7.7   
14            1      apple  golden_delicious   152    7.6     7.3   
15            1      apple  golden_delicious   156    7.7     7.1   
16            1      apple  golden_delicious   156    7.6     7.5   
17            1      apple  golden_delicious   168    7.5     7.6   
18            1      apple       cripps_pink   162    7.5     7.1   
19            1      apple       cripps_pink   162    7.4     7.2   
20            1      apple       cripps_pink   160    7.5     7.5   
21            1      apple       cripps_pink   156    7.4     7.4   
22            1      apple       cripps_pink   140    7.3     7.1   
23            1      apple       cripps_pink   170    7.6     7.9   
24            3     orange     spanish_jumbo   342    9.0     9.4   
25            3     orange     spanish_jumbo   356    9.2     9.2   
26            3     orange     spanish_jumbo   362    9.6     9.2   
27            3     orange  selected_seconds   204    7.5     9.2   
28            3     orange  selected_seconds   140    6.7     7.1   
29            3     orange  selected_seconds   160    7.0     7.4   
30            3     orange  selected_seconds   158    7.1     7.5   
31            3     orange  selected_seconds   210    7.8     8.0   
32            3     orange  selected_seconds   164    7.2     7.0   
33            3     orange      turkey_navel   190    7.5     8.1   
34            3     orange      turkey_navel   142    7.6     7.8   
35            3     orange      turkey_navel   150    7.1     7.9   
36            3     orange      turkey_navel   160    7.1     7.6   
37            3     orange      turkey_navel   154    7.3     7.3   
38            3     orange      turkey_navel   158    7.2     7.8   
39            3     orange      turkey_navel   144    6.8     7.4   
40            3     orange      turkey_navel   154    7.1     7.5   
41            3     orange      turkey_navel   180    7.6     8.2   
42            3     orange      turkey_navel   154    7.2     7.2   
43            4      lemon    spanish_belsan   194    7.2    10.3   
44            4      lemon    spanish_belsan   200    7.3    10.5   
45            4      lemon    spanish_belsan   186    7.2     9.2   
46            4      lemon    spanish_belsan   216    7.3    10.2   
47            4      lemon    spanish_belsan   196    7.3     9.7   
48            4      lemon    spanish_belsan   174    7.3    10.1   
49            4      lemon           unknown   132    5.8     8.7   
50            4      lemon           unknown   130    6.0     8.2   
51            4      lemon           unknown   116    6.0     7.5   
52            4      lemon           unknown   118    5.9     8.0   
53            4      lemon           unknown   120    6.0     8.4   
54            4      lemon           unknown   116    6.1     8.5   
55            4      lemon           unknown   116    6.3     7.7   
56            4      lemon           unknown   116    5.9     8.1   
57

In [46]:
fruits4.fruit_label2.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [47]:
lookup_lname = dict()
lookup_lname

{}

In [48]:
c = fruits4.fruit_label2
cc = len(c)
cc

59

In [49]:
for i in range(cc):
    lookup_lname[fruits4.fruit_label2[i]] = fruits4.fruit_label[i]
lookup_lname

{0: 1, 1: 2, 2: 1, 3: 1, 4: 1, 5: 3, 6: 3, 7: 3, 8: 4, 9: 4}

In [50]:
fr_pred

array([5, 7, 8, 9, 2, 2, 7, 6, 7, 9, 1, 3, 4, 2, 8])

In [51]:
y_te = np.array(y_test)
y_te

array([5, 7, 8, 6, 2, 0, 7, 8, 7, 4, 1, 2, 6, 7, 7])

In [52]:
fr_pred = [lookup_lname[i] for i in fr_pred]
fr_pred

[3, 3, 4, 4, 1, 1, 3, 3, 3, 4, 2, 1, 1, 1, 4]

In [53]:
y_te = [lookup_lname[i] for i in y_te]
y_te

[3, 3, 4, 3, 1, 1, 3, 4, 3, 1, 2, 1, 3, 3, 3]

In [54]:
(fr_pred,y_te)

([3, 3, 4, 4, 1, 1, 3, 3, 3, 4, 2, 1, 1, 1, 4],
 [3, 3, 4, 3, 1, 1, 3, 4, 3, 1, 2, 1, 3, 3, 3])

In [55]:
z = [a - b for a, b in zip(fr_pred,y_te)]
z

[0, 0, 0, 1, 0, 0, 0, -1, 0, 3, 0, 0, -2, -2, 1]

In [56]:
len(z)

15

In [57]:
z.count(0)

9

In [59]:
#accuracy
accur = (z.count(0) / len(z))
accur

0.6